services:
   php-fpm:
     build: 
      args:
        user: saitam
        uid: 1000
      context: ./php8-fpm
     container_name: php8-fpm
     volumes:
       - ./src:/var/www/html
       - ./php8-fpm/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
       - ./php8-fpm/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

   nginx:
     build: ./nginx
     restart: always
     container_name: nginx
     ports:
       - "80:80"
     volumes:
       - "./src:/var/www/html"
       - "./nginx/default:/etc/nginx/conf.d/default.conf"
     depends_on:
       - php-fpm

   db:
     image: mysql:8.0
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     container_name: mysql1
     environment:
       MYSQL_ROOT_PASSWORD: secret
     volumes:
       - "./db:/var/lib/mysql"
     ports:
      - "3306:3306"

   phpmyadmin:
     image: phpmyadmin
     container_name: phpmyadmin1
     restart: always
     ports:
       - 8080:80
     
networks:
  default:
    external: true
    name: mysql-network


